
    Vagrant.configure("2") do |config|
        config.vm.box = "generic/ubuntu2004"
        config.vm.hostname = "YDFce"

        config.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 2
        end
    
        config.vm.provision "shell", path: "../init_vm.sh"
        config.vm.provision "docker"
        config.vm.provision "file", source: "../container_configurator.py", destination: "app.py"
        config.vm.provision "file", source: "../function_container.py", destination: "function_container.py"
        config.vm.provision "file", source: "../exception_container.py", destination: "exception_container.py"

        #network configuration
        config.vm.network :forwarded_port, guest: 5002, host: 5002, id: "container_server"
        config.vm.network "public_network", bridge: "veth-YDFce-peer", ip: "10.1.3.10"

    end
    